version: '3'

services:
  eid:
    image: eid
    build: 
      context: eid
    container_name: eid
    restart: always
    network_mode: bridge
    links:
      - mysql:mysql
      - ldap:ldap
    ports:
      - 8080:8080

  shibboleth:
    image: shibboleth
    build:
      context: shibboleth
    container_name: shibboleth
    restart: always
    network_mode: bridge
    links:
      - ldap:ldap
    ports:
      - 443:443
      - 8443:8443
        
  ldap:
    image: ldap
    build: 
      context: ldap
    container_name: ldap
    restart: always
    network_mode: bridge
    volumes:
      - ldap:/var/lib/ldap

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    network_mode: bridge
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=SENHA_MYSQL"

volumes:
  ldap:
  mysql:
